### ISSUE TITLE
Unexpected identified with typescript (and node non experimental?)

### ISSUE THREAD

**Issue by Nerothos** [Kaprisa/koa-expect#1]
Hi,
Thanks for creating this middleware.
I'm trying to use koa-expect but I got an error :

```
node_modules/koa-expect/index.mjs:1
(function (exports, require, module, __filename, __dirname) { import expect from './src/expect';
                                                                     ^^^^^^

SyntaxError: Unexpected identifier
    at new Script (vm.js:79:7)
    at createScript (vm.js:251:10)
    at Object.runInThisContext (vm.js:303:10)
    at Module._compile (internal/modules/cjs/loader.js:657:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (routes/index.js:5:22)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
error Command failed with exit code 1.
```

I think this happen because I'm using typescript and do a simple node to launch my project but from the glances of it, the middleware is written for using the experimental import.

I'm not sure if you can do something about it since it would probably mean to rewrote all the es6 things but it's just for noticing you.

**Comment by Kaprisa** [comment]
Hi, 
I've fixed it.

**Comment by Nerothos** [comment]
Thanks.
